services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: $MAGE_CODE_PATH/${PROJECT_NAME}
      ENV: dev
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
      - ./models:$MAGE_CODE_PATH/models
      # Store the data output on local machine for easier debugging
      - ~/.mage_data:/$MAGE_CODE_PATH/mage_data
      # IAM user credentials
      - ~/.aws:/root/.aws
      # Local machine’s SSH keys
      - ~/.ssh:/root/.ssh:ro
      
    restart: on-failure:5
    networks:
      app-network:
        aliases:
          - mlflow
    depends_on:
      - magic-database
    stdin_open: true # for interactive debugging
    tty: true # for interactive debugging
  magic-database:
    image: pgvector/pgvector:0.6.0-pg16
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ~/.postgres/data:/var/lib/postgresql/data
      # Custom database initialization scripts
      - ./scripts/database:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - app-network
  mlflow:
    build: 
      context: .
      dockerfile: mlflow.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "${PWD}/mlflow_data:/home/mlflow_data/"
      - "${PWD}/mlartifacts:/mlartifacts/"
      - "${PWD}/models:/models/"
    networks:
      - app-network
  # prediction-webservice:
  #   build:
  #     context: .
  #     dockerfile: predictservice.dockerfile
  #   environment:
  #     MLFLOW_TRACKING_URI: http://mlflow:5000
  #   volumes:
  #     - .:/home/src/
  #     # IAM user credentials
  #     - ~/.aws:/root/.aws
  #     # Local machine’s SSH keys
  #     - ~/.ssh:/root/.ssh:ro
  #   ports:
  #     - "9696:9696"
  #   networks:
  #     - app-network
networks:
  app-network:
    driver: bridge